name: asf_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Securley store data in a keystore
  flutter_secure_storage: ^3.3.1+1

  # Nano core functions
  nanodart: ^1.0.0

  # Shared prefs
  shared_preferences: ^0.5.6+2

  # Flare for animations
  flare_flutter: ^2.0.1

  # Websockets
  web_socket_channel: ^1.1.0

  # Platform-specific build info
  package_info: ^0.4.0+14

  # Device-specific info
  device_info: ^0.4.1+5

  # JSON Serialization
  json_annotation: ^3.0.1

  # Localization
  intl: ^0.16.0

  # BigDecimal alternative
  decimal: ^0.3.5

  # Logger
  logger: ^0.8.3

  # Native webview plugin
  flutter_webview_plugin: ^0.3.10+1

  # SQLite
  sqflite: ^1.2.1

  # Android/iOS path provider
  path_provider: ^1.6.1

  # TouchID/FaceID
  local_auth: ^0.6.1+3

  # Eventbus
  event_taxi: ^0.1.5

  # SVG
  flutter_svg: ^0.17.1

  # QR Codes
  qr_flutter: ^2.0.1 # Generator
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  # File picker
  file_picker: ^1.4.3+2

  # Deep link support
  #uni_links: ^0.2.0
  uni_links:
    git:
      url: https://github.com/CathalT/uni_links.git
      ref: nfc_android

  # HTTP client
  http: ^0.12.0+4

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.2.0

  # Push notifications
  firebase_messaging: ^6.0.9

  # Slidable list actions
  flutter_slidable: ^0.5.4

  # Lock helper
  synchronized: ^2.2.0

  # Service provider
  get_it: ^3.1.0

  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master

  # Validation utilities
  validators: ^2.0.0+1

  # Auto resize text widget
  auto_size_text: ^2.1.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: ^0.1.2

  flutter_easyloading: ^1.0.1

  # Manta dart implementation
  manta_dart:
    git:
      url: https://github.com/bbedward/manta-dart.git
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
